# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'WSDynamicAlbumMakerDemo' do

  pod 'CTAssetsPickerController'
  pod 'MBProgressHUD', '~> 0.9.1'

end

target 'WSDynamicAlbumMakerDemoTests' do

end
